### ISSUE TITLE
Clicking on save is creating a never ending operation in progress dialog

### ISSUE THREAD

**Issue by chauhanvats3** [creati8e/AutoTagger-Issues#2] opened 2019-08-26 10:18 UTC
I have to close app from task manager and then open it again after every edit. Although the edit is happening successfully, but the dialog is not going away.

![Screenshot_20190826-154533](https://user-images.githubusercontent.com/25562174/63683755-d338dc00-c818-11e9-9088-3bc6f73c25bd.jpg)

**Comment by creati8e** [comment] 2019-08-26 13:00
Thanks for letting me know! Do you use an auto renaming?

**Comment by chauhanvats3** [comment] 2019-08-26 13:31
Yes i did.
And now that i have disabled auto renaming,its not getting stuck on that
dialog.
What should i do to fix this?

**Comment by creati8e** [comment] 2019-08-26 13:53
Hmm. It seems that auto renaming is cause of stucking. You don't need to do anything. I need to investigate and fix this issue.

**Comment by chauhanvats3** [comment] 2019-08-26 13:55
Okay. Thanks. Will be waiting for the update.
And, great update to the app, loved everything about the update. Thanks.

**Comment by creati8e** [comment] 2019-08-27 12:13
@chauhanvats3 i've put some fixes into code. Can you try is this problem solved or not? (i'll send you an updated apk)

**Comment by chauhanvats3** [comment] 2019-08-27 12:19
Yeah sure.

**Comment by creati8e** [comment] 2019-08-27 14:58
@chauhanvats3 please test it on files which causes a hung.
https://rink.hockeyapp.net/apps/984566d9c474440caa06724d9db9494b/app_versions/3

**Comment by chauhanvats3** [comment] 2019-08-27 15:12
The problem is persisting still

**Comment by creati8e** [comment] 2019-08-27 15:51
Huh. 
Can you share your setup? (where your file is located, auto renaming pattern, file itself)

**Comment by chauhanvats3** [comment] 2019-08-27 19:31
Here is the pattern, the stuck screen, file does gets renamed even if i
force close the app, as displayed but its in another pattern i.e. track
number is also there which shouldnt be. Is there any way i can send you the
logs, maybe they'll help debug the problem?

**Comment by creati8e** [comment] 2019-08-27 19:34
Logs is disabled in release APK. Just send me your pattern and your file. It will be easier to reproduce issue in the same environment.

**Comment by chauhanvats3** [comment] 2019-08-27 19:45
I have tried all the patterns on multiple files. And the issue is
consistent. Still, if you say, here is one of the files.

**Comment by creati8e** [comment] 2019-09-05 17:46
@chauhanvats3 hi again! I've found another few possible causes of these hangs. Can you try an updated version, please? https://rink.hockeyapp.net/apps/984566d9c474440caa06724d9db9494b/app_versions/4

**Comment by chauhanvats3** [comment] 2019-09-05 18:28
Still not working.
The file is getting renamed for the desired pattern.
But the service is not ending after that.
Is that not happening for you?

**Comment by creati8e** [comment] 2019-09-05 18:33
No. I only can reproduce if I intentionally create an incorrect state. But I've fixed these states.

**Comment by chauhanvats3** [comment] 2019-09-05 18:36
If the operation in process dialog is for a background thread, can you try
replacing it with service with notification instead?

**Comment by creati8e** [comment] 2019-09-05 18:40
Don't sure because tag saving for one song is quick operation. But for long operations it can make a sense.

**Comment by creati8e** [comment] 2019-09-05 18:41
So you experiencing this issue when put app in background during tag saving and then open again?

**Comment by chauhanvats3** [comment] 2019-09-05 18:43
No, i am facing the issue in normal usage that is pressing save button and waiting for operation to end.

**Comment by creati8e** [comment] 2019-09-05 18:47
Please give me steps to reproduce. You said that in some cases dialog is finished. 
Write what you do when edit song. And send me file, please.

**Comment by chauhanvats3** [comment] 2019-09-05 18:50
Should i make a video of it and send it to you ?

**Comment by creati8e** [comment] 2019-09-05 18:51
Video is good, and file too.

**Comment by chauhanvats3** [comment] 2019-09-05 19:00
https://drive.google.com/folderview?id=1Al9Uk6PgsW3n7Z8NzfMmW738GWR8RWAH

Here is a video of whats happening and one of the audio files.

**Comment by creati8e** [comment] 2019-09-05 19:08
Thanks. But still can't reproduce 🤦‍♂️

**Comment by chauhanvats3** [comment] 2019-09-05 19:18
Maybe its an issue with my phone.
Nothing I can do about it from my side if that's the case.
Can you try reproducing it in a OnePlus 5T?

**Comment by creati8e** [comment] 2019-09-05 19:23
No, I can't. Do you have android 10? I can try to make another debug build tomorrow.  A big thanks to you for participating.

**Comment by chauhanvats3** [comment] 2019-09-05 19:25
No, It's android 9.
Thanks to you too for making this awesome app.

**Comment by creati8e** [comment] 2019-09-07 13:17
@chauhanvats3 hi again! i've added additional logs in new build. 
Please try it. When you will finish with track editing, click on the notification and send logs here or on my email gregamer@gmail.com
https://install.appcenter.ms/users/gregamer-gmail.com/apps/autotagger-1/distribution_groups/all-users-of-autotagger

**Comment by creati8e** [comment] 2019-09-11 20:05
@chauhanvats3 i've installed OxygenOS 9 and can reproduce dialog stucking!

**Comment by chauhanvats3** [comment] 2019-09-11 20:46
Ohh, it was the OS that was causing the issue. So, what did you find out?

**Comment by creati8e** [comment] 2019-09-11 20:48
MediaStore (and MediaScanner) is cause of stucking. It just does not scan file after renaming.

**Comment by creati8e** [comment] 2019-09-13 09:01
Fixed in 3.0.3

**Closed by creati8e** 2019-09-13 09:01 UTC
Labels: bug
